import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import products from '../products.json';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Games App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://app.snipcart.com" />
<link rel="preconnect" href="https://cdn.snipcart.com" />
<link rel="stylesheet" href="https://cdn.snipcart.com/themes/v3.0.21/default/snipcart.css" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.header}>My Gaming App</h1>
      <div className={styles.grid}>
  {products.map(product => {
    return (
      <div key={product.id} className={styles.card}>
        <h3 className={styles.title}>{ product.title }</h3>
        <img src={product.image} alt={`Preview of ${product.title}`}  className={styles.image}/>
        <p className={styles.description}>{ product.description }</p>
        <p className={styles.price}>Rs.{ product.price }</p>
        <p className={styles.btn}>
        <button className="snipcart-add-item"
  data-item-id={product.id}
  data-item-image={product.image}
  data-item-name={product.title}
  data-item-price={product.price} 
>
  Add to Cart
</button>
        </p>
      </div>
      
    );
  })}
</div>
      </main>
      <footer className={styles.footer}>
        <button >More Details</button>
        <br/>
        <button>Reviews</button>  
      </footer>
      <script async src="https://cdn.snipcart.com/themes/v3.0.21/default/snipcart.js" />
      <div hidden id="snipcart" data-api-key="MjE4Y2UxNjgtNGYyMS00YjcxLTkyNGYtZmM5Yjc0YzA4MzIxNjM4MTIxMTQyMTExOTkzNjA4" />
      
    </>
  )
}
